import { createSlice } from "@reduxjs/toolkit";

// Initial state for meetings slice
const initialState = {
  // Array to hold toast notifications
  toasts: [],
};

// Create a Redux slice for meetings related state and reducers
export const meetingsSlice = createSlice({
  name: "meetings",
  initialState,
  reducers: {
    // Reducer to set the toasts array
    setToasts: (state, action) => {
      state.toasts = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const { setToasts } = meetingsSlice.actions;
